export enum RolePermissionType {
	CUSTOMERS_WRITE,
	CUSTOMERS_READ,

	CATEGORIES_READ,
	CATEGORIES_WRITE,

	ITEMS_WRITE,
	ITEMS_READ,

	WAREHOUSE_ITEMS_WRITE,
	WAREHOUSE_ITEMS_READ,

	EMPLOYEES_READ,
	EMPLOYEES_WRITE,

	WAREHOUSES_WRITE,
	WAREHOUSES_READ,

	CARS_WRITE,
	CARS_READ,

	DISPATCHING_APPLICATIONS_READ,
	DISPATCHING_APPLICATIONS_WRITE,

	ALL_APPLICATIONS_READ,
	ALL_APPLICATIONS_WRITE,

	ACCOUNT_READ,
	ACCOUNT_WRITE,

	WRITE_OFF_READ_ALL,
	WRITE_OFF_READ_BY_WAREHOUSE,
	WRITE_OFF_READ_BY_DRIVER,
	WRITE_OFF_WRITE,

	ALL_WAYBILLS_READ,
	ALL_WAYBILLS_WRITE,

	STATE_TAXES_READ
}
